### ISSUE TITLE
CT object is not compatible with merge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/griddle#66]
```
griddle : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/griddle_en.html?continuousTest=%7B%22test%22%3A%5B%22griddle%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641397075%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/XYCursorPlot.js:50:5)
at Object.demoXYCursorPlot [as createNode] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/demo/GriddleDemoScreenView.js:489:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sun/js/demo/DemosScreenView.js:129:24
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

griddle : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/griddle_en.html?continuousTest=%7B%22test%22%3A%5B%22griddle%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599646954172%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/XYCursorPlot.js:50:5)
at Object.demoXYCursorPlot [as createNode] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/demo/GriddleDemoScreenView.js:489:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sun/js/demo/DemosScreenView.js:129:24
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

griddle : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/griddle_en.html?continuousTest=%7B%22test%22%3A%5B%22griddle%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641390959%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: object is not compatible with merge
Error: Assertion failed: object is not compatible with merge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at assertIsMergeable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:59:3)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:31:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sherpa/lib/lodash-4.17.4.js:9359:14)
at merge (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-core/js/merge.js:29:5)
at new ScrollingChartNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/ScrollingChartNode.js:45:15)
at new XYCursorPlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/XYCursorPlot.js:50:5)
at Object.demoXYCursorPlot [as createNode] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/griddle/js/demo/GriddleDemoScreenView.js:489:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/sun/js/demo/DemosScreenView.js:129:24
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM
```

**Comment by jessegreenberg** [comment]
Sorry about that, fixed in the above commit.
